name: CI

on:
  push:
    # Avoid duplicate builds on PRs.
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run ShellCheck bin top level
        run: |
            shellcheck bin/* -x
      - name: Run shfmt
        uses: docker://mvdan/shfmt:latest
        with:
          args: "--diff ."
